#ifndef MONSTERATTRS_H
#define MONSTERATTRS_H


#define FLY_BLUE_MONSTER_BLOOD 15
#define FLY_BLUE_MONSTER_SPEED 2
#define FLY_BLUE_MONSTER_ATT_RANGE 1
#define FLY_BLUE_MONSTER_DAMAGE 2


#define PINK_MONSTER_BLOOD 15
#define PINK_MONSTER_SPEED 1
#define PINK_MONSTER_ATT_RANGE 1
#define PINK_MONSTER_DAMAGE 1


#define STAR_MONSTER_BLOOD 20
#define STAR_MONSTER_SPEED 1
#define STAR_MONSTER_ATT_RANGE 1
#define STAR_MONSTER_DAMAGE 1

#define M_AFFIX_SLOTS 2


#define BLINK_ATTR 1
#define AGILITY_ATTR 2

#endif // MONSTERATTRS_H
